groups:
  - name: prometheus-alerts
    rules:
      - alert: PrometheusTargetDown
        expr: |
          sum by (juju_application) (
            up{juju_application="prometheus-k8s", juju_model="observability"} == 0
          ) > 0
        for: 15m
        labels:
          severity: critical
          team: observability
          juju_model_uuid: "e9f39fb5-e6ff-4e0c-82a5-712bdd7e1912"
          juju_application: "prometheus-k8s"
          juju_model: "observability"
        annotations:
          summary: Prometheus target is down
          description: At least one scrape target is down for {{ $labels.juju_application }}
