groups:
  - name: invalid-promql-rule-2
    rules:
      - alert: InvalidPromQLRule
        expr: |
          sum by (juju_application) (
            up{juju_application="prometheus-k8s", juju_model="observability} == 0
          ) > 0
        for: 15m
        labels:
          severity: critical
          team: some-team
        annotations:
          summary: Invalid PromQL rule
          description: This rule is intentionally VERY VERY INVALID FOR TESTING.
